#!/bin/bash
PATH="/opt/pacbio/smrtlink/install/smrtlink-release_25.1.0.257715/admin/bin/../../bundles/smrttools/current/private/otherbins/all/bin:/opt/pacbio/smrtlink/install/smrtlink-release_25.1.0.257715/admin/bin/../../bundles/smrtlink-analysisservices-gui/current/private/pacbio/smrtlink-analysisservices-gui/tools/binwrap:/usr/bin:/usr/bin:/bin"

cd /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution
tmpDir=$(([ -z "$SINGULARITY_NAME" ] && mkdir -p $(readlink -m /opt/pacbio/smrtlink/userdata/tmp_dir) && mktemp -d /opt/pacbio/smrtlink/userdata/tmp_dir/cromwell_tmp.XXXXXX) || (mkdir -p /tmp/mydir && echo /tmp/mydir))

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution

)
out3fd734da="${tmpDir}/out.$$" err3fd734da="${tmpDir}/err.$$"
mkfifo "$out3fd734da" "$err3fd734da"
trap 'rm "$out3fd734da" "$err3fd734da"' EXIT
touch '/opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/stdout' '/opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/stderr'
tee '/opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/stdout' < "$out3fd734da" &
tee '/opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/stderr' < "$err3fd734da" >&2 &
(
cd /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution


python3 \
  -m pbcoretools.tasks.auto_ccs_outputs_barcoded \
  --log-level INFO \
  --nproc 29 \
  `readlink -f /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/inputs/-1968187755/m84151_241230_115705_s1.hifi_reads.consensusreadset.xml` \
  ccs_demultiplexed_outputs.datastore.json
)  > "$out3fd734da" 2> "$err3fd734da"
echo $? > /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution



)
mv /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/rc.tmp /opt/pacbio/analysis/cromwell-executions/pb_demux_ccs/3fd734da-1a0f-43cb-98b6-12446616f47c/call-auto_ccs_outputs_barcoded/execution/rc
